/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MAST;


import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class MastApplication {
 
    public static void main(String[] args) {
        SpringApplication.run(MastApplication.class, args);
    }
 
}
