/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MAST;


import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;

@SpringBootApplication
public class MastApplication extends SpringBootServletInitializer {
 

 
    public static void main(String[] args) {
        SpringApplication.run(MastApplication.class, args);
    }
 
}
